version: '3'

services:
  db:
    image: mysql:8.0
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MY_PASSWORD}
      MYSQL_DATABASE: "mobiusdb"
      TZ: Asia/Seoul 
    ports:
      - 3306:3306
    volumes:
      - ./Mobius/mobius/mobiusdb.sql:/docker-entrypoint-initdb.d/mobiusdb.sql:ro
      - ./db/data:/var/lib/mysql:rw
      - /etc/localtime:/etc/localtime:ro 
      # - ./db/conf.d:/etc/mysql/conf.d # Uncomment if you want to apply custom configuration file.
    healthcheck:
      test: ["CMD", "mysqladmin" ,"--password=${MY_PASSWORD}","ping"]
      interval: 20s
      timeout: 20s
      retries: 5
  node:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: node
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development # development, production
      - USE_CLUSTERING=0 # 0 = false, 1 = true
      - MY_PASSWORD=${MY_PASSWORD}
    volumes:
      - ./Mobius:/home/node/app
    ports:
      - 7577-7579:7577-7579
      - 7582:7582
    command:
      - bash
      - -c
      - |
        /wait-for-it.sh db:3306 -t 20 -s
        /wait-for-it.sh mqtt:1883 -t 20 -s
        node mobius
    depends_on:
      db:
        condition: service_healthy
        
  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mqtt
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto/config:/mosquitto/config:ro
      - ./var/log/mosquitto:/var/log/mosquitto:rw
    depends_on:
      db:
        condition: service_healthy